### ISSUE TITLE
integration

### ISSUE THREAD

**Issue by wanghaisheng** [nbilbo/flet-alchemy#1]
can you try to integrate this https://github.com/farshadz1997/Microsoft-Rewards-bot-GUI-V2 into your code
I have managed  but failed
https://github.com/wanghaisheng/flet-tiktoka-studio

**Comment by nbilbo** [comment]
your idea is to ask the user for a username and password to access the microsoft rewards bot?

**Comment by wanghaisheng** [comment]
something kinda of that.
i was thinking to find a minimal saas starter based on flet. and  your alchemey is  best ,but I can not figure out the  logic, especially  route after login  success to homepage when I try to add  microsoft rewards bot pages to your your default home page . login page just disappear .

**Comment by wanghaisheng** [comment]
at the same time  I want to know  how to build backend service based on SQLAlchemy ,there is fastapi also using SQLAlchemy

**Comment by nbilbo** [comment]
I think it's because the projects followed different ways to configure the application.

**Comment by wanghaisheng** [comment]
does flet has any recommendation or best practise about configure application ?

>at the same time I want to know how to build backend service based on SQLAlchemy ,there is fastapi also using SQLAlchemy
what about this?

**Comment by nbilbo** [comment]
You can divide your tasks as:
1. Learn how to build a rest-api using fastapi.
2. Apply some designer pattern using flet to handle complex applications (mvc for example).
3. Put it all together using docker-compose.
Its just a idea.

**Comment by wanghaisheng** [comment]
1.  I can do this now
2. i need to learn this topic  ,first of look at flet-alchemy ,what I thought of this something like that
do you have recommendations?

**Comment by wanghaisheng** [comment]
@nbilbo 
https://github.com/wanghaisheng/flet-saas-starter

I have renamed the repo

**Comment by nbilbo** [comment]
really nice. I think that the next step is each user have your own accounts. Currently is used a json file to store the accounts.

**Comment by wanghaisheng** [comment]
that is a great idea  SQLite should be a start solution and honestly  with  SQLalchemy we can manage to have more powerful user management service.
personally  I have concerns about stripe integrations. with this it kinda of be  a MVP anyone who works on a tool solution can benefit from
